# Generated by Django 4.1.5 on 2023-01-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='charity',
            table='charity',
        ),
    ]
