# Generated by Django 4.1.5 on 2023-01-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_charity_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='doner_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='doner_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='doner_mob',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='doner_name',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='charity',
            table='charitys',
        ),
    ]
